import numpy as np
import matplotlib.pyplot as plt
fc1 = np.load('./hessian_inverse/fc1.npy')
print(fc1.shape)
# print(fc1)
fc2 = np.load('./hessian_inverse/fc2.npy')
print(fc2.shape)
fc3 = np.load('./hessian_inverse/fc3.npy')
print(fc3.shape)
fc1_batch0 = np.load('./layer_inputs/fc1/batch_0.npy')
print(fc1_batch0.shape)
fc2_batch0 = np.load('./layer_inputs/fc2/batch_0.npy')
print(fc2_batch0.shape)
fc3_batch0 = np.load('./layer_inputs/fc3/batch_0.npy')
print(fc3_batch0.shape)
orig_w1 = np.load('./original_parameters/w_layer1.npy')
print(orig_w1.shape, orig_w1)
orig_b1 = np.load('./original_parameters/b_layer1.npy')
print(orig_b1.shape, orig_b1)
orig_w2 = np.load('./original_parameters/w_layer2.npy')
print(orig_w2.shape)
orig_b2 = np.load('./original_parameters/b_layer2.npy')
print(orig_b2.shape)
orig_w3 = np.load('./original_parameters/w_layer3.npy')
print(orig_w3.shape)
orig_b3 = np.load('./original_parameters/b_layer3.npy')
print(orig_b3.shape)
pruned_w1 = np.load('./pruned_parameters/fc1/weights.npy')
print(pruned_w1.shape)
pruned_b1 = np.load('./pruned_parameters/fc1/biases.npy')
print(pruned_b1.shape)
pruned_w2 = np.load('./pruned_parameters/fc2/weights.npy')
print(pruned_w2.shape)
pruned_b2 = np.load('./pruned_parameters/fc2/biases.npy')
print(pruned_b2.shape)
pruned_w3 = np.load('./pruned_parameters/fc3/weights.npy')
print(pruned_w3.shape)
pruned_b3 = np.load('./pruned_parameters/fc3/biases.npy')
print(pruned_b3.shape)

# orig_b1 = np.load('./original_parameters/b_layer1.npy')
# pruned_b1 = np.load('./pruned_parameters/fc1/biases.npy')
# print(orig_b1)
# print(pruned_b1)
# plt.plot(orig_b1)
# plt.plot(pruned_b1)
plt.show()

#print(fc1, fc2, fc3)